export const CLINICALTNOTES = 'CLINICALTNOTES';
export const CLINICALTNOTES_SUCCESS = 'CLINICALTNOTES_SUCCESS';
export const CLINICALTNOTES_ERROR = 'CLINICALTNOTES_ERROR';

export const CLINICALTNOTES_GET = 'CLINICALTNOTES_GET';
export const CLINICALTNOTES_GET_SUCCESS = 'CLINICALTNOTES_GET_SUCCESS';
export const CLINICALTNOTES_GET_ERROR = 'CLINICALTNOTES_GET_ERROR';

export const CLINICALTNOTES_CREATE = 'CLINICALTNOTES_CREATE';
export const CLINICALTNOTES_CREATE_SUCCESS = 'CLINICALTNOTES_CREATE_SUCCESS';
export const CLINICALTNOTES_CREATE_ERROR = 'CLINICALTNOTES_CREATE_ERROR';

export const CLINICALTNOTES_UPDATE = 'CLINICALTNOTES_UPDATE';
export const CLINICALTNOTES_UPDATE_SUCCESS = 'CLINICALTNOTES_UPDATE_SUCCESS';
export const CLINICALTNOTES_UPDATE_ERROR = 'CLINICALTNOTES_UPDATE_ERROR';
