export const CLINICALTSTATEMENTS = 'CLINICALTSTATEMENTS';
export const CLINICALTSTATEMENTS_SUCCESS = 'CLINICALTSTATEMENTS_SUCCESS';
export const CLINICALTSTATEMENTS_ERROR = 'CLINICALTSTATEMENTS_ERROR';

export const CLINICALTSTATEMENTS_GET = 'CLINICALTSTATEMENTS_GET';
export const CLINICALTSTATEMENTS_GET_SUCCESS = 'CLINICALTSTATEMENTS_GET_SUCCESS';
export const CLINICALTSTATEMENTS_GET_ERROR = 'CLINICALTSTATEMENTS_GET_ERROR';

export const CLINICALTSTATEMENTS_CREATE = 'CLINICALTSTATEMENTS_CREATE';
export const CLINICALTSTATEMENTS_CREATE_SUCCESS = 'CLINICALTSTATEMENTS_CREATE_SUCCESS';
export const CLINICALTSTATEMENTS_CREATE_ERROR = 'CLINICALTSTATEMENTS_CREATE_ERROR';

export const CLINICALTSTATEMENTS_UPDATE = 'CLINICALTSTATEMENTS_UPDATE';
export const CLINICALTSTATEMENTS_UPDATE_SUCCESS = 'CLINICALTSTATEMENTS_UPDATE_SUCCESS';
export const CLINICALTSTATEMENTS_UPDATE_ERROR = 'CLINICALTSTATEMENTS_UPDATE_ERROR';
