export const CLINICALSTATEMENTS = 'CLINICALSTATEMENTS';
export const CLINICALSTATEMENTS_SUCCESS = 'CLINICALSTATEMENTS_SUCCESS';
export const CLINICALSTATEMENTS_ERROR = 'CLINICALSTATEMENTS_ERROR';

export const CLINICALSTATEMENTS_GET = 'CLINICALSTATEMENTS_GET';
export const CLINICALSTATEMENTS_GET_SUCCESS = 'CLINICALSTATEMENTS_GET_SUCCESS';
export const CLINICALSTATEMENTS_GET_ERROR = 'CLINICALSTATEMENTS_GET_ERROR';

export const CLINICALSTATEMENTS_CREATE = 'CLINICALSTATEMENTS_CREATE';
export const CLINICALSTATEMENTS_CREATE_SUCCESS = 'CLINICALSTATEMENTS_CREATE_SUCCESS';
export const CLINICALSTATEMENTS_CREATE_ERROR = 'CLINICALSTATEMENTS_CREATE_ERROR';

export const CLINICALSTATEMENTS_UPDATE = 'CLINICALSTATEMENTS_UPDATE';
export const CLINICALSTATEMENTS_UPDATE_SUCCESS = 'CLINICALSTATEMENTS_UPDATE_SUCCESS';
export const CLINICALSTATEMENTS_UPDATE_ERROR = 'CLINICALSTATEMENTS_UPDATE_ERROR';
