export const GENERIC_PLUGIN = 'GENERIC_PLUGIN';
export const GENERIC_PLUGIN_SUCCESS = 'GENERIC_PLUGIN_SUCCESS';
export const GENERIC_PLUGIN_ERROR = 'GENERIC_PLUGIN_ERROR';

export const GENERIC_PLUGIN_GET = 'GENERIC_PLUGIN_GET';
export const GENERIC_PLUGIN_GET_SUCCESS = 'GENERIC_PLUGIN_GET_SUCCESS';
export const GENERIC_PLUGIN_GET_ERROR = 'GENERIC_PLUGIN_GET_ERROR';

export const GENERIC_PLUGIN_CREATE = 'GENERIC_PLUGIN_CREATE';
export const GENERIC_PLUGIN_CREATE_SUCCESS = 'GENERIC_PLUGIN_CREATE_SUCCESS';
export const GENERIC_PLUGIN_CREATE_ERROR = 'GENERIC_PLUGIN_CREATE_ERROR';

export const GENERIC_PLUGIN_UPDATE = 'GENERIC_PLUGIN_UPDATE';
export const GENERIC_PLUGIN_UPDATE_SUCCESS = 'GENERIC_PLUGIN_UPDATE_SUCCESS';
export const GENERIC_PLUGIN_UPDATE_ERROR = 'GENERIC_PLUGIN_UPDATE_ERROR';
